const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mib = bytes => (Number(bytes) / 1048576).toFixed(1);

export function buildReport(summary, results, runId = summary.runId) {
  // Formatting only: all measurements, IDs, hashes and outcomes come from receipts.
  const rank = label => label === 'before' ? 0 : 1;
  const profiles = ['low', 'balanced', 'wide'];
  const downloads = results.filter(x => x.mode === 'download').slice().sort((a,b) => rank(a.label) - rank(b.label) || profiles.indexOf(a.profile) - profiles.indexOf(b.profile));
  const blocks = results.filter(x => x.mode === 'blocks').slice().sort((a,b) => rank(a.label) - rank(b.label));
  const rows = downloads.map(x => `<tr><td>${esc(x.expectedSdkVersion)}</td><td>${esc(x.profile)}</td><td>${x.maximumConcurrency} &times; ${x.maximumTransferMiB}</td><td>${x.rangeWindowEstimateMiB}</td><td>${mib(x.sampledPeakManagedBytes - x.baselineManagedBytes)}</td><td>${mib(x.sampledPeakWorkingSetBytes - x.baselineWorkingSetBytes)}</td><td>${x.rangeRequests.length}</td><td>${Number(x.elapsedMilliseconds).toFixed(0)}</td><td>${esc(x.status)}</td></tr>`).join('');
  const cards = blocks.map(x => `<article><h3>${x.label === 'before' ? 'Before' : 'After'} &mdash; ${esc(x.expectedSdkVersion)}</h3><p>Block IDs shared between two uploads: <strong>${x.sdkBlockIds?.overlap ?? '?'}/8</strong></p><p>First upload, then second upload, in committed order:</p><pre>${esc(x.sdkBlockIds?.first?.join('\n'))}\n\n${esc(x.sdkBlockIds?.second?.join('\n'))}</pre></article>`).join('');
  const checks = blocks.map(x => `<article><h3>${esc(x.expectedSdkVersion)} &mdash; ${x.checks.length} checks</h3><ul>${x.checks.map(c => `<li>${c.pass ? 'PASS' : 'FAIL'} &mdash; ${esc(c.name)}</li>`).join('')}</ul></article>`).join('');
  const after = blocks.find(x => x.label === 'after');
  const runtime = results[0]?.runtime;
  const os = results[0]?.os;
  return `<!doctype html>
<html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Azure Blob SDK 12.30: Local Comparison Proof</title>
<style>body{font-family:Segoe UI,Tahoma,sans-serif;background:#eef2f6;color:#172435;margin:0;padding:32px;line-height:1.7}main{max-width:1250px;margin:auto}section{background:#fff;border:1px solid #d5deea;border-radius:12px;margin:22px 0;padding:24px}h1,h2,h3{line-height:1.4}h1{font-size:28px}.pass{color:#087a45}.fail{color:#b52126}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}article{background:#f7f9fc;padding:16px;border-radius:8px}pre{overflow:auto;font-size:12px;white-space:pre-wrap;word-break:break-all;text-align:left}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:center}small{color:#526174}.table{overflow-x:auto}@media(max-width:800px){body{padding:10px}.grid{grid-template-columns:1fr}}</style></head>
<body><main><h1>Azure Blob SDK: Local Comparison Proof</h1>
<p><b class="${summary.status === 'PASS' ? 'pass' : 'fail'}">${esc(summary.status)} &mdash; ${summary.passedChecks} checks passed; ${summary.crossVersionChecks?.length ?? 0} cross-version gates</b> | Azurite ${esc(summary.azuriteVersion ?? '3.37.0')} | ${esc(summary.utc)}</p>
<p>Azure.Storage.Blobs 12.29.2 vs 12.30.0. Real SDK operations against a local emulator, with no Azure account. Service API: 2023-11-03.</p>
${summary.error ? `<section><h2>Run error</h2><pre>${esc(summary.error)}</pre></section>` : ''}
<section id="block-ids"><h2>1. Block IDs Across Two Uploads</h2><p>We upload 8 MiB twice to the same blob name, forcing eight blocks per upload. These are the actual block IDs returned by storage.</p><div class="grid">${cards}</div></section>
<section id="resume"><h2>2. Resume, Commit Order, and Writer Protection</h2><p>After a deliberate interruption following two staged blocks, we reload the manifest from disk, resume the upload, commit the ordered list, and verify SHA256. Reversing the list changes the file bytes; restoring the original order restores the hash. This reload occurs within the same process; it does not simulate a power failure.</p><p>A second writer uses a stale ETag: <b>HTTP ${after?.etagGuard?.staleWriterHttpStatus ?? '?'}</b>. Different block IDs alone do not prevent another writer from replacing the blob.</p><div class="grid">${checks}</div></section>
<section id="memory"><h2>3. Download Settings and Memory Measurements</h2><p>64 MiB fixture; every successful download matches the source SHA256. Each row runs in a fresh .NET process and writes to a disk file, not a MemoryStream. Memory is sampled every 10 ms.</p><div class="table"><table><thead><tr><th>SDK</th><th>Profile</th><th>C &times; chunk MiB</th><th>Range window estimate MiB</th><th>Managed peak &Delta; MiB</th><th>Working set peak &Delta; MiB</th><th>GET ranges</th><th>ms</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div><p><strong>C &times; chunk estimates the range-size window; it is not a process memory cap.</strong> Buffer pools, network buffers, garbage collection, and warm-up affect the observations. Measurements need not increase in row order; the proof does not require a particular improvement percentage.</p><p>These are local observations, not Azure throughput measurements or production memory guarantees. InitialTransferSize is set explicitly; MaximumTransferSize does not automatically limit the first request.</p></section>
<section id="limits"><h2>Proof Scope</h2><p>Azurite tests SDK behavior and local storage operations. It does not establish Azure service latency, scalability, or behavior under heavy concurrent load. The ETag test uses two sequential conditional commits after staging blocks for two writers. The cancellation test uses a token canceled before the download starts.</p><small>Run: ${esc(runId)}<br>Runtime: ${esc(runtime)}<br>OS: ${esc(os)}</small></section>
</main></body></html>`;
}
